/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package BalancedGroupings3

import kotlin.test.Test
import kotlin.test.assertEquals

class BalancedGroupingTest {
    @Test fun WhitespaceTest() {
        val classUnderTest = BalancedGroupingsProblem()
        assertEquals(true, classUnderTest.isBalanced("   "))
    }
}
