/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package BalancedGroupings3

class BalancedGroupingsProblem {
    fun isBalanced(sequence: String): Boolean {
        return true
    }
}
