/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package BalancedGroupings3

import java.util.ArrayDeque

class BalancedGroupingsProblem {
    fun isBalanced(sequence: String): Boolean {
        val stack = ArrayDeque<Char>()

        for (c in sequence) {
            if (c == '(' || c == '[' || c == '{')
                stack.push(c)
        }

        if (stack.size > 0)
            return false
        else
            return true  
    }
}
